FROM adoptopenjdk:11-jre-hotspot
LABEL maintainer="sonya.tochko@live.com"
VOLUME /main-app-volume
ADD target/advertising_platform-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar","/app.jar"]

#\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes\




