spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/advertising_platform
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#tochko:
#  advertising_platform:
#    jwtSecret: testSecret
#    jwtExpirationMs: 86400000



